# Generated by Django 3.0.3 on 2020-02-16 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseModel')),
                ('count', models.PositiveIntegerField(default=0)),
                ('upvotes', models.ManyToManyField(related_name='like', to='core.Picture')),
            ],
            bases=('core.basemodel',),
        ),
    ]
