# Generated by Django 3.0.3 on 2020-02-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
    ]
